---
title: "Basic or advanced statistics"
site: bookdown::bookdown_site
output: 
  bookdown::pdf_book
---

```{r include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  message = FALSE
)
library(tidyverse)
library(ordinal)
library(scales)
```

```{r}
status <- read_csv("../../data/status.csv") %>%
  mutate(
    Church = factor(Church),
    Lights = factor(
      Lights,
      levels = c("not", "half", "full"),
      labels = c("dark", "partly lit", "fully lit")
    ),
    Period = factor(
      Period,
      levels = c("80's", "2016")
    ),
    Status = factor(
      Status,
      levels = c("colony", "used", "no bats"),
      ordered = TRUE
    )
  )
```

```{r}
contrasts <- function(model, contrast, n = 1000){
  cf <- summary(model)$coef
  params <- rnorm(
    n * nrow(cf), 
    mean = cf[, "Estimate"], 
    sd = cf[, "Std. Error"]
  ) %>%
    matrix(nrow = nrow(cf))
  contrast %*% params
}
```

```{r}
current_model <- clm(Status ~ Lights, data = status, subset = Period == "2016")
drop1(current_model, test = "Chisq")
summary(current_model)
```

```{r}
cumulative_logit <- contrasts(
  current_model, 
  contrast =  rbind(
    "colony:dark" = c(1, 0, 0, 0),
    "colony:partly lit" = c(1, 0, -1, 0),
    "colony:fully lit" = c(1, 0, 0, -1),
    "colony or used:dark" = c(0, 1, 0, 0),
    "colony or used:partly lit" = c(0, 1, -1, 0),
    "colony or used:fully lit" = c(0, 1, 0, -1)
  )
)
cumulative_prediction <- cumulative_logit %>%
  plogis() %>%
  apply(
    1, 
    function(x){
      c(
        Mean = mean(x), 
        LCL = quantile(x, 0.025) %>%
          unname(), 
        UCL = quantile(x, 0.975) %>%
          unname()
      )
    }
  ) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Contrast") %>%
  extract(Contrast, c("Status", "Lights"), "(.*):(.*)") %>%
  mutate(Lights = factor(Lights, levels = levels(status$Lights)))
```

```{r base-model, fig.cap = "Estimated cumulative probability based on the 2016 dataset."}
ggplot(
  cumulative_prediction, 
  aes(
    x = Lights, 
    y = Mean, ymin = LCL, ymax = UCL, 
    colour = Status
  )
) +
  geom_errorbar(position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5)) +
  scale_y_continuous(
    "Estimated cumulative probability",
    labels = percent, 
    limits = 0:1
  )
```

  
```{r}
status_model <- clmm(Status ~ Period + Lights + (1|Church), data = status)
drop1(status_model, test = "Chisq")
summary(status_model)
```

```{r}
cumulative_logit <- contrasts(
  status_model, 
  contrast =  rbind(
    "colony:80's:dark" = c(1, 0, 0, 0, 0),
    "colony:2016:dark" = c(1, 0, -1, 0, 0),
    "colony:2016:partly lit" = c(1, 0, -1, -1, 0),
    "colony:2016:fully lit" = c(1, 0, -1, 0, -1),
    "colony or used:80's:dark" = c(0, 1, 0, 0, 0),
    "colony or used:2016:dark" = c(0, 1, -1, 0, 0),
    "colony or used:2016:partly lit" = c(0, 1, -1, -1, 0),
    "colony or used:2016:fully lit" = c(0, 1, -1, 0, -1)
  )
)
cumulative_prediction <- cumulative_logit %>%
  plogis() %>%
  apply(
    1, 
    function(x){
      c(
        Mean = mean(x), 
        LCL = quantile(x, 0.025) %>%
          unname(), 
        UCL = quantile(x, 0.975) %>%
          unname()
      )
    }
  ) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Contrast") %>%
  extract(Contrast, c("Status", "Period", "Lights"), "(.*):(.*):(.*)")
```

```{r time-model, fig.cap = "Estimated cumulative probability"}
ggplot(
  cumulative_prediction, 
  aes(
    x = Lights, 
    y = Mean, ymin = LCL, ymax = UCL, 
    colour = Status, 
    shape = Period, linetype = Period
  )
) +
  geom_errorbar(position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5)) +
  scale_y_continuous(
    "Estimated cumulative probability",
    labels = percent, 
    limits = 0:1
  ) + 
  coord_flip()
```

```{r}
status %>%
  filter(Period == "2016") %>%
  count(Lights, Renovated, Status)
```


```{r}
renovation_model <- clmm(
  Status ~ Period + Lights + Renovated + (1|Church), 
  data = status
)
drop1(renovation_model, test = "Chisq")
summary(renovation_model)
```

```{r}
cumulative_logit <- contrasts(
  renovation_model, 
  contrast =  rbind(
    "colony:80's:dark:no" = c(1, 0, 0, 0, 0, 0),
    "colony or used:80's:dark:no" = c(0, 1, 0, 0, 0, 0),
    "colony:2016:dark:no" = c(1, 0, -1, 0, 0, 0),
    "colony:2016:partly lit:no" = c(1, 0, -1, -1, 0, 0),
    "colony:2016:fully lit:no" = c(1, 0, -1, 0, -1, 0),
    "colony or used:2016:dark:no" = c(0, 1, -1, 0, 0, 0),
    "colony or used:2016:partly lit:no" = c(0, 1, -1, -1, 0, 0),
    "colony or used:2016:fully lit:no" = c(0, 1, -1, 0, -1, 0),
    "colony:2016:dark:yes" = c(1, 0, -1, 0, 0, -1),
    "colony:2016:partly lit:yes" = c(1, 0, -1, -1, 0, -1),
    "colony:2016:fully lit:yes" = c(1, 0, -1, 0, -1, -1),
    "colony or used:2016:dark:yes" = c(0, 1, -1, 0, 0, -1),
    "colony or used:2016:partly lit:yes" = c(0, 1, -1, -1, 0, -1),
    "colony or used:2016:fully lit:yes" = c(0, 1, -1, 0, -1, -1)
  )
)
cumulative_prediction <- cumulative_logit %>%
  plogis() %>%
  apply(
    1, 
    function(x){
      c(
        Mean = mean(x), 
        LCL = quantile(x, 0.025) %>%
          unname(), 
        UCL = quantile(x, 0.975) %>%
          unname()
      )
    }
  ) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Contrast") %>%
  extract(
    Contrast, 
    c("Status", "Period", "Lights", "Renovation"), 
    "(.*):(.*):(.*):(.*)"
  ) %>%
  mutate(
    Period = ifelse(
      Period == "2016",
      Renovation,
      Period
    ) %>%
      factor(
        levels = c("80's", "no", "yes"),
        labels = c("80's", "2016", "2016 with\nrenovation")
      ),
    Lights = factor(Lights, levels = levels(status$Lights))
  )
```

```{r renovation-model, fig.cap = "Estimated cumulative probability"}
ggplot(
  cumulative_prediction, 
  aes(
    x = Lights, 
    y = Mean, ymin = LCL, ymax = UCL, 
    colour = Period
  )
) +
  geom_errorbar(position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5)) +
  scale_x_discrete("Light status 2016") +
  scale_y_continuous(
    "Estimated cumulative probability",
    labels = percent, 
    limits = 0:1
  ) + 
  facet_wrap(~Status)
```
