---
title: "Data wrangling and exploration"
author: "Thierry Onkelinx"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = TRUE,
  message = FALSE
)
```

```{r packages}
library(readxl)
library(tidyverse)
library(DT)
```

```{r import-data}
raw_data <- read_excel("../original/rsos161077supp1.xlsx", n_max = 111) %>%
  slice(-1) %>%
  select(
    Church = 1, Lights = 10, Status80 = 5, Status16 = 11
  )
```

```{r echo = FALSE}
datatable(raw_data)
```

```{r}
status <- raw_data %>%
  mutate(
    Church = factor(Church),
    Lights = factor(
      Lights, 
      levels = c("not", "half", "full")
    ),
    Paired = !is.na(Status80) & !is.na(Status16),
    Status80 = factor(
      Status80, 
      levels = c("no bats", "used", "colony"),
      ordered = TRUE
    ),
    Status16 = gsub("\\?", "", Status16) %>%
      factor(
        levels = c("no bats", "used", "colony"),
        ordered = TRUE
      ) 
  ) %>%
  gather("Period", "Status", Status80, Status16) %>%
  filter(!is.na(Status)) %>%
  mutate(
    Period = factor(
      Period == "Status80", 
      levels = c(TRUE, FALSE),
      labels = c("80's", "2016")
    ),
    Status = factor(
      Status,
      levels = c("no bats", "used", "colony"),
      ordered = TRUE
    ) 

  )
```

```{r}
status %>%
  count(Paired, Period, Status) %>%
  spread(Status, n) %>%
  kable()
```

```{r}
status %>%
  count(Paired, Status, Period, Lights) %>%
  spread(Lights, n, fill = 0) %>%
  kable()
```

```{r}
write_csv(status, "../data/status.csv")
```

